/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as CustomerAboutRouteImport } from './routes/_customer/about'
import { Route as CustomerContactRouteImport } from './routes/_customer/contact'
import { Route as CustomerMenuRouteImport } from './routes/_customer/menu'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminHoursRouteImport } from './routes/admin/hours'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminMenuItemsRouteImport } from './routes/admin/menu-items'
import { Route as AdminPromotionsRouteImport } from './routes/admin/promotions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSocialsRouteImport } from './routes/admin/socials'
import { Route as CustomerMenuCategoryRouteImport } from './routes/_customer/menu.$category'
import { Route as AdminMenuItemsIdRouteImport } from './routes/admin/menu-items.$id'
import { Route as AdminMenuItemsNewRouteImport } from './routes/admin/menu-items.new'

const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAboutRoute = CustomerAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerContactRoute = CustomerContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuItemsRoute = AdminMenuItemsRouteImport.update({
  id: '/menu-items',
  path: '/menu-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialsRoute = AdminSocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerMenuCategoryRoute = CustomerMenuCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CustomerMenuRoute,
} as any)
const AdminMenuItemsIdRoute = AdminMenuItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMenuItemsRoute,
} as any)
const AdminMenuItemsNewRoute = AdminMenuItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMenuItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof CustomerAboutRoute
  '/contact': typeof CustomerContactRoute
  '/menu': typeof CustomerMenuRouteWithChildren
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/': typeof AdminIndexRoute
  '/menu/$category': typeof CustomerMenuCategoryRoute
  '/admin/menu-items/$id': typeof AdminMenuItemsIdRoute
  '/admin/menu-items/new': typeof AdminMenuItemsNewRoute
}
export interface FileRoutesByTo {
  '/about': typeof CustomerAboutRoute
  '/contact': typeof CustomerContactRoute
  '/menu': typeof CustomerMenuRouteWithChildren
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/': typeof CustomerIndexRoute
  '/admin': typeof AdminIndexRoute
  '/menu/$category': typeof CustomerMenuCategoryRoute
  '/admin/menu-items/$id': typeof AdminMenuItemsIdRoute
  '/admin/menu-items/new': typeof AdminMenuItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_customer/about': typeof CustomerAboutRoute
  '/_customer/contact': typeof CustomerContactRoute
  '/_customer/menu': typeof CustomerMenuRouteWithChildren
  '/admin/account': typeof AdminAccountRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/_customer/': typeof CustomerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_customer/menu/$category': typeof CustomerMenuCategoryRoute
  '/admin/menu-items/$id': typeof AdminMenuItemsIdRoute
  '/admin/menu-items/new': typeof AdminMenuItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/menu'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/socials'
    | '/admin/'
    | '/menu/$category'
    | '/admin/menu-items/$id'
    | '/admin/menu-items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/menu'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/socials'
    | '/'
    | '/admin'
    | '/menu/$category'
    | '/admin/menu-items/$id'
    | '/admin/menu-items/new'
  id:
    | '__root__'
    | '/_customer'
    | '/admin'
    | '/_customer/about'
    | '/_customer/contact'
    | '/_customer/menu'
    | '/admin/account'
    | '/admin/categories'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/socials'
    | '/_customer/'
    | '/admin/'
    | '/_customer/menu/$category'
    | '/admin/menu-items/$id'
    | '/admin/menu-items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRoute: typeof CustomerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/about': {
      id: '/_customer/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof CustomerAboutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/contact': {
      id: '/_customer/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof CustomerContactRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/menu': {
      id: '/_customer/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-items': {
      id: '/admin/menu-items'
      path: '/menu-items'
      fullPath: '/admin/menu-items'
      preLoaderRoute: typeof AdminMenuItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/socials': {
      id: '/admin/socials'
      path: '/socials'
      fullPath: '/admin/socials'
      preLoaderRoute: typeof AdminSocialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/menu/$category': {
      id: '/_customer/menu/$category'
      path: '/$category'
      fullPath: '/menu/$category'
      preLoaderRoute: typeof CustomerMenuCategoryRouteImport
      parentRoute: typeof CustomerMenuRoute
    }
    '/admin/menu-items/$id': {
      id: '/admin/menu-items/$id'
      path: '/$id'
      fullPath: '/admin/menu-items/$id'
      preLoaderRoute: typeof AdminMenuItemsIdRouteImport
      parentRoute: typeof AdminMenuItemsRoute
    }
    '/admin/menu-items/new': {
      id: '/admin/menu-items/new'
      path: '/new'
      fullPath: '/admin/menu-items/new'
      preLoaderRoute: typeof AdminMenuItemsNewRouteImport
      parentRoute: typeof AdminMenuItemsRoute
    }
  }
}

interface CustomerMenuRouteChildren {
  CustomerMenuCategoryRoute: typeof CustomerMenuCategoryRoute
}

const CustomerMenuRouteChildren: CustomerMenuRouteChildren = {
  CustomerMenuCategoryRoute: CustomerMenuCategoryRoute,
}

const CustomerMenuRouteWithChildren = CustomerMenuRoute._addFileChildren(
  CustomerMenuRouteChildren,
)

interface CustomerRouteChildren {
  CustomerAboutRoute: typeof CustomerAboutRoute
  CustomerContactRoute: typeof CustomerContactRoute
  CustomerMenuRoute: typeof CustomerMenuRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAboutRoute: CustomerAboutRoute,
  CustomerContactRoute: CustomerContactRoute,
  CustomerMenuRoute: CustomerMenuRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface AdminMenuItemsRouteChildren {
  AdminMenuItemsIdRoute: typeof AdminMenuItemsIdRoute
  AdminMenuItemsNewRoute: typeof AdminMenuItemsNewRoute
}

const AdminMenuItemsRouteChildren: AdminMenuItemsRouteChildren = {
  AdminMenuItemsIdRoute: AdminMenuItemsIdRoute,
  AdminMenuItemsNewRoute: AdminMenuItemsNewRoute,
}

const AdminMenuItemsRouteWithChildren = AdminMenuItemsRoute._addFileChildren(
  AdminMenuItemsRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenuItemsRoute: typeof AdminMenuItemsRouteWithChildren
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialsRoute: typeof AdminSocialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenuItemsRoute: AdminMenuItemsRouteWithChildren,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialsRoute: AdminSocialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CustomerRoute: CustomerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
